# For a direct USB cable connection, the port name is typically
# /dev/ttyACM# where is # is a number such as 0, 1, 2, etc
# For a wireless connection like XBee, the port is typically
# /dev/ttyUSB# where # is a number such as 0, 1, 2, etc.

port: /dev/ttyACM1
baud: 57600
timeout: 0.1

rate: 50
sensorstate_rate: 10

use_base_controller: True
base_controller_rate: 10      #Rate to publish odometry data. 

# For a robot that uses base_footprint, change base_frame to base_footprint
base_frame: base_link

# === Robot drivetrain parameters
wheel_diameter: 0.1916 #0.188         #Wheel diameter in meters.
wheel_track: 0.407           #Distance between centers of drive wheels.
encoder_resolution: 4480        #Encoder ticks per wheel revolution.
gear_reduction: 1.0           #External gear reduction.
motors_reversed: False        #Reverse the sense of wheel rotation. 

# === PID parameters
Kp: 2
Kd: 0
Ki: 0
Ko: 70
accel_limit: 1.0              #Max acceleration when changing wheel speeds (default 0.1)

# === Sensor definitions.  Examples only - edit for your robot.
#     Sensor type can be one of the follow (case sensitive!):
#	  * Ping
#	  * GP2D12
#	  * Analog
#	  * Digital
#	  * PololuMotorCurrent
#	  * PhidgetsVoltage
#	  * PhidgetsCurrent (20 Amp, DC)



sensors: {
  #motor_current_left:   {pin: 0, type: PololuMotorCurrent, rate: 5},
  #motor_current_right:  {pin: 1, type: PololuMotorCurrent, rate: 5},
  #ir_front_center:      {pin: 2, type: GP2D12, rate: 10},
  #sonar_front_center:   {pin: 5, type: Ping, rate: 10},
  #encoder_A:            {pin:  2, type: Digital, rate: 5, direction: output},
  #encoder_B:            {pin:  3, type: Digital, rate: 5, direction: output},
  #arduino_led:          {pin: 13, type: Digital, rate: 5, direction: output}
}
