// Generated by gencpp from file web_robot_communication/ModeChanges.msg
// DO NOT EDIT!


#ifndef WEB_ROBOT_COMMUNICATION_MESSAGE_MODECHANGES_H
#define WEB_ROBOT_COMMUNICATION_MESSAGE_MODECHANGES_H

#include <ros/service_traits.h>


#include <web_robot_communication/ModeChangesRequest.h>
#include <web_robot_communication/ModeChangesResponse.h>


namespace web_robot_communication
{

struct ModeChanges
{

typedef ModeChangesRequest Request;
typedef ModeChangesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModeChanges
} // namespace web_robot_communication


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::web_robot_communication::ModeChanges > {
  static const char* value()
  {
    return "4f7a1d450bc2c8872a872f31f56ded53";
  }

  static const char* value(const ::web_robot_communication::ModeChanges&) { return value(); }
};

template<>
struct DataType< ::web_robot_communication::ModeChanges > {
  static const char* value()
  {
    return "web_robot_communication/ModeChanges";
  }

  static const char* value(const ::web_robot_communication::ModeChanges&) { return value(); }
};


// service_traits::MD5Sum< ::web_robot_communication::ModeChangesRequest> should match
// service_traits::MD5Sum< ::web_robot_communication::ModeChanges >
template<>
struct MD5Sum< ::web_robot_communication::ModeChangesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::web_robot_communication::ModeChanges >::value();
  }
  static const char* value(const ::web_robot_communication::ModeChangesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::web_robot_communication::ModeChangesRequest> should match
// service_traits::DataType< ::web_robot_communication::ModeChanges >
template<>
struct DataType< ::web_robot_communication::ModeChangesRequest>
{
  static const char* value()
  {
    return DataType< ::web_robot_communication::ModeChanges >::value();
  }
  static const char* value(const ::web_robot_communication::ModeChangesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::web_robot_communication::ModeChangesResponse> should match
// service_traits::MD5Sum< ::web_robot_communication::ModeChanges >
template<>
struct MD5Sum< ::web_robot_communication::ModeChangesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::web_robot_communication::ModeChanges >::value();
  }
  static const char* value(const ::web_robot_communication::ModeChangesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::web_robot_communication::ModeChangesResponse> should match
// service_traits::DataType< ::web_robot_communication::ModeChanges >
template<>
struct DataType< ::web_robot_communication::ModeChangesResponse>
{
  static const char* value()
  {
    return DataType< ::web_robot_communication::ModeChanges >::value();
  }
  static const char* value(const ::web_robot_communication::ModeChangesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEB_ROBOT_COMMUNICATION_MESSAGE_MODECHANGES_H
