// Generated by gencpp from file web_robot_communication/ModeChangesRequest.msg
// DO NOT EDIT!


#ifndef WEB_ROBOT_COMMUNICATION_MESSAGE_MODECHANGESREQUEST_H
#define WEB_ROBOT_COMMUNICATION_MESSAGE_MODECHANGESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace web_robot_communication
{
template <class ContainerAllocator>
struct ModeChangesRequest_
{
  typedef ModeChangesRequest_<ContainerAllocator> Type;

  ModeChangesRequest_()
    : mode()  {
    }
  ModeChangesRequest_(const ContainerAllocator& _alloc)
    : mode(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::web_robot_communication::ModeChangesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::web_robot_communication::ModeChangesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ModeChangesRequest_

typedef ::web_robot_communication::ModeChangesRequest_<std::allocator<void> > ModeChangesRequest;

typedef boost::shared_ptr< ::web_robot_communication::ModeChangesRequest > ModeChangesRequestPtr;
typedef boost::shared_ptr< ::web_robot_communication::ModeChangesRequest const> ModeChangesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::web_robot_communication::ModeChangesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::web_robot_communication::ModeChangesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::web_robot_communication::ModeChangesRequest_<ContainerAllocator1> & lhs, const ::web_robot_communication::ModeChangesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::web_robot_communication::ModeChangesRequest_<ContainerAllocator1> & lhs, const ::web_robot_communication::ModeChangesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace web_robot_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::web_robot_communication::ModeChangesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::web_robot_communication::ModeChangesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_robot_communication::ModeChangesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_robot_communication::ModeChangesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_robot_communication::ModeChangesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_robot_communication::ModeChangesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::web_robot_communication::ModeChangesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e84dc3ad5dc323bb64f0aca01c2d1eef";
  }

  static const char* value(const ::web_robot_communication::ModeChangesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe84dc3ad5dc323bbULL;
  static const uint64_t static_value2 = 0x64f0aca01c2d1eefULL;
};

template<class ContainerAllocator>
struct DataType< ::web_robot_communication::ModeChangesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "web_robot_communication/ModeChangesRequest";
  }

  static const char* value(const ::web_robot_communication::ModeChangesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::web_robot_communication::ModeChangesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string mode\n"
;
  }

  static const char* value(const ::web_robot_communication::ModeChangesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::web_robot_communication::ModeChangesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModeChangesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::web_robot_communication::ModeChangesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::web_robot_communication::ModeChangesRequest_<ContainerAllocator>& v)
  {
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEB_ROBOT_COMMUNICATION_MESSAGE_MODECHANGESREQUEST_H
