// Generated by gencpp from file web_robot_communication/ModeChangesResponse.msg
// DO NOT EDIT!


#ifndef WEB_ROBOT_COMMUNICATION_MESSAGE_MODECHANGESRESPONSE_H
#define WEB_ROBOT_COMMUNICATION_MESSAGE_MODECHANGESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace web_robot_communication
{
template <class ContainerAllocator>
struct ModeChangesResponse_
{
  typedef ModeChangesResponse_<ContainerAllocator> Type;

  ModeChangesResponse_()
    : message()  {
    }
  ModeChangesResponse_(const ContainerAllocator& _alloc)
    : message(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::web_robot_communication::ModeChangesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::web_robot_communication::ModeChangesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ModeChangesResponse_

typedef ::web_robot_communication::ModeChangesResponse_<std::allocator<void> > ModeChangesResponse;

typedef boost::shared_ptr< ::web_robot_communication::ModeChangesResponse > ModeChangesResponsePtr;
typedef boost::shared_ptr< ::web_robot_communication::ModeChangesResponse const> ModeChangesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::web_robot_communication::ModeChangesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::web_robot_communication::ModeChangesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::web_robot_communication::ModeChangesResponse_<ContainerAllocator1> & lhs, const ::web_robot_communication::ModeChangesResponse_<ContainerAllocator2> & rhs)
{
  return lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::web_robot_communication::ModeChangesResponse_<ContainerAllocator1> & lhs, const ::web_robot_communication::ModeChangesResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace web_robot_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::web_robot_communication::ModeChangesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::web_robot_communication::ModeChangesResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_robot_communication::ModeChangesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::web_robot_communication::ModeChangesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_robot_communication::ModeChangesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::web_robot_communication::ModeChangesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::web_robot_communication::ModeChangesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f003d6bcc824cbd51361d66d8e4f76c";
  }

  static const char* value(const ::web_robot_communication::ModeChangesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f003d6bcc824cbdULL;
  static const uint64_t static_value2 = 0x51361d66d8e4f76cULL;
};

template<class ContainerAllocator>
struct DataType< ::web_robot_communication::ModeChangesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "web_robot_communication/ModeChangesResponse";
  }

  static const char* value(const ::web_robot_communication::ModeChangesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::web_robot_communication::ModeChangesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string message\n"
;
  }

  static const char* value(const ::web_robot_communication::ModeChangesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::web_robot_communication::ModeChangesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModeChangesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::web_robot_communication::ModeChangesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::web_robot_communication::ModeChangesResponse_<ContainerAllocator>& v)
  {
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEB_ROBOT_COMMUNICATION_MESSAGE_MODECHANGESRESPONSE_H
