odom_frame: odom
base_link_frame: base_link
world_frame: odom

two_d_mode: true

frequency: 10

odom0: /odom
odom0_config: [false, false, false,   # x,   y,   z
              false, false, false,   # r,   p,   w (yaw)
              true,  false,  false,    # dx,  dy,  dz
              false, false, false,    # dr,  dp,  dw
              false, false, false]   # ddx, ddy, ddz
odom0_differential: false
odom0_nodelay: true
odom0_queue_size: 10

# odom1: /t265/odom/sample
# odom1_config: [false, false, false,   # x,   y,   z
#               false, false, false,   # r,   p,   w (yaw)
#               true,  true,  false,    # dx,  dy,  dz
#               false, false, true,    # dr,  dp,  dw
#               false, false, false]   # ddx, ddy, ddz
# odom1_differential: false
# odom1_nodelay: true
# odom1_queue_size: 10

#imu0: /mavros/imu/data_raw
#imu0_config: [false, false, false,   # x,   y,   z
#              false, false, false,   # r,   p,   w (yaw)
#              false, false, false,   # dx,  dy,  dz
#              true,  true,  true,    # dr,  dp,  dw
#              false, false, false]   # ddx, ddy, ddz
#imu0_differential: true
#imu0_nodelay: true
#imu0_queue_size: 10
#imu0_remove_gravitational_acceleration: true

imu0: /mavros/imu/data
imu0_config: [false, false, false,   # x,   y,   z
             true, true, true,   # r,   p,   w (yaw)
             false, false, false,   # dx,  dy,  dz
             true, true, true,    # dr,  dp,  dw
             false,  false,  false]   # ddx, ddy, ddz
imu0_differential: true
imu0_nodelay: true
imu0_queue_size: 10
imu0_remove_gravitational_acceleration: true

#imu1: /t265/gyro/sample
#imu1_config: [false, false, false,   # x,   y,   z
#             false, false, false,   # r,   p,   w (yaw)
#             false, false, false,   # dx,  dy,  dz
#             false,  true,  false,    # dr,  dp,  dw
#             false, false, false]   # ddx, ddy, ddz
#imu1_differential: true
#imu1_nodelay: true
#imu1_queue_size: 10
#imu1_remove_gravitational_acceleration: true
